- name: Configure Jenkins Master
  hosts: jenkins_master
  roles:
    - role: libs-install
      tags: libs-install
    - role: docker-install
      tags: docker-install
    - role: jenkins-install
      tags: jenkins-install