- name: Docker install
  block:
    - name: Install Universe repository
      ansible.builtin.apt_repository:
        state: present
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    - name: Install libs
      ansible.builtin.apt:
        state: present
        update_cache: true
        cache_valid_time: 3600
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
  become: true
