all:
  children:
    jenkins_master:
      hosts:
        linux_jenkins_master:
          ansible_host: 51.250.95.64
          ansible_port: 22
          ansible_user: punchman
          ansible_ssh_private_key_file: .ssh_key
